# .github/workflows/remote-browser.yml

name: Remote Browser Worker

on:
  workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - name: Install Playwright
        run: |
          npx playwright install chromium

      - name: Install GUI dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            xvfb \
            x11-utils \
            xclip \
            xsel \
            fluxbox \
            wmctrl \
            libgtk-3-0 \
            libgbm1 \
            libasound2t64 \
            libxshmfence1 \
            libnss3 \
            libxss1 \
            libatk-bridge2.0-0 \
            libdrm2 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libu2f-udev \
            libvulkan1

      - name: Start virtual display
        run: |

          export DISPLAY=:99

          Xvfb :99 \
            -screen 0 1920x1080x24 \
            > /dev/null 2>&1 &

          fluxbox > /dev/null 2>&1 &

          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Start dispatcher
        env:
          DISPLAY: :99
        run: |
          node dispatcher.js
